# Generated by Django 5.0.4 on 2024-05-07 08:11

import django.core.validators
import signup.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least one digit.', regex='[0-9]'), django.core.validators.RegexValidator(message='Password must contain at least one lowercase letter.', regex='[a-z]'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter.', regex='[A-Z]')])),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to=signup.models.user_directory_path)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least one digit.', regex='[0-9]'), django.core.validators.RegexValidator(message='Password must contain at least one lowercase letter.', regex='[a-z]'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter.', regex='[A-Z]')])),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to=signup.models.user_directory_path)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', signup.models.CustomUserManager()),
            ],
        ),
    ]
