# Generated by Django 5.0.4 on 2024-05-07 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least one digit.', regex='[0-9]'), django.core.validators.RegexValidator(message='Password must contain at least one lowercase letter.', regex='[a-z]'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter.', regex='[A-Z]')]),
        ),
    ]
