# Generated by Django 5.0.4 on 2024-05-13 15:50

import addrecipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(default='', max_length=100)),
                ('disc', models.TextField(blank=True, default='')),
                ('cusine', models.CharField(blank=True, default='', max_length=100)),
                ('ocasion', models.CharField(blank=True, default='', max_length=100)),
                ('ingreds', models.TextField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
                ('cook_time', models.IntegerField(blank=True, null=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, default=0)),
                ('carbs', models.FloatField(blank=True, default=0)),
                ('image', models.ImageField(upload_to=addrecipe.models.recipe_directory_path)),
            ],
        ),
    ]
