# Generated by Django 5.0.4 on 2024-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isfav',
            field=models.BooleanField(default=False),
        ),
    ]
