# Generated by Django 5.0.4 on 2024-05-14 00:05

import addcuisine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(default='', max_length=100)),
                ('disc', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to=addcuisine.models.recipe_directory_path)),
            ],
        ),
    ]
